name: robot_brain
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pip
  - pip:
    - fastapi==0.109.0
    - uvicorn==0.27.0
    - pydantic==2.5.3
    - websockets==12.0
    - numpy==1.26.3
    - torch==2.1.2
    - torchvision==0.16.2
    - opencv-python==4.9.0.80
    - python-multipart==0.0.6
    - python-jose==3.3.0
    - passlib==1.7.4
    - bcrypt==4.1.2
    - python-dotenv==1.0.0
    - pyyaml==6.0.1
    - pytest==7.4.4
    - pytest-asyncio==0.23.3
    - pytest-cov==4.1.0
    - black==23.12.1
    - isort==5.13.2
    - mypy==1.8.0
    - flake8==7.0.0 