name: fastvlm
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.1.0
  - torchvision
  - cudatoolkit=11.8
  - pip
  - pip:
    - fastapi==0.104.1
    - uvicorn==0.24.0
    - python-multipart==0.0.6
    - websockets==12.0
    - opencv-python==4.8.1.78
    - numpy==1.24.3
    - pillow==10.0.0
    - transformers==4.35.0
    - timm==0.9.12 